# fly.toml app configuration file generated for toyproject-sns on 2023-06-01T01:55:05+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "toyproject-sns"
primary_region = "nrt"

[build]
  image = "Dockerfile"
# image = "nginx"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
