name: Fly Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: toyproject-sns
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deply --remote-onlt
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}


